import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './Providers';
import { ToastProvider } from './ToastProvider';
import { Navbar } from '@/components/ui/Navbar';
import { AuthNavbarWrapper } from '@/components/ui/AuthNavbarWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased`}>
        <Providers>
          <ToastProvider>
            <AuthNavbarWrapper />
            <main className="pt-16">{children}</main>
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
